### PR TITLE
Duplicate email fix

### PR DESCRIPTION
**Pull request by karapetianarthur**
Duplicate email fix

### CODE REVIEW

**Comment by claytonrothschild** [comment]
Thanks. Next time commit to the same PR. You can add commits to the same PR even after its opened.

**Comment by claytonrothschild** [comment]
Also, once I give feedback and feedback is completed request my review again on the PR so I know its ready for review and merging. Else I dont know when you are dont committing etc. So I will wait for another review request before closing this one.

**Comment by karapetianarthur** [comment]
Clayton, recapping what I got from your messages: when I commit any change I ask you to review it. When you approve it, then I create a pull request, after I pend for your approval, right?

**Comment by karapetianarthur** [comment]
> Also, once I give feedback and feedback is completed request my review again on the PR so I know its ready for review and merging. Else I dont know when you are dont committing etc. So I will wait for another review request before closing this one.

Clayton, recapping what I got from your messages: when I commit any change I ask you to review it. When you approve it, then I create a pull request, after I pend for your approval, right?

**Pull request closed without merging**
